#!/usr/bin/python

# Copyright (c) 2014 Nikolay Yakovlev
# All Rights Reserved.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

from gi.repository import Gtk
from tickets import Tickets
from tododo import ToDoDo
from tododo import Settings

class Do():
    def __init__(self):
        tickets = Tickets(Settings)

        main_window = ToDoDo(tickets)
        main_window.connect("delete-event", Gtk.main_quit)
        main_window.show_all()
        Gtk.main()

if __name__ == '__main__':
    do = Do()
